# Generated by Django 4.1.3 on 2022-12-01 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completion',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 10, 30, 6, 537527)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 10, 30, 6, 537502)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_echeance',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 10, 30, 6, 537539)),
        ),
    ]
